<a href="https://colab.research.google.com/github/Revanth-Desai/GPA-Prediction-Application/blob/main/GPA_Prediction_Application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_excel('/content/OOP Lab - Data.xlsx')

In [ ]:
data

S.No  Registration No              Student Name  Internal Marks  \
0       1        209301007           NIKHIL BHANDARI              47   
1       2        209301011                 IVA SETHI              47   
2       3        209301020      JASKARAN SINGH BARMI              49   
3       4        209301037               NITYA ARORA              47   
4       5        209301041    HARSHIT KUMAR METPALLY              49   
..    ...              ...                       ...             ...   
112   113        209302115         TANISHA CHAUDHARY              54   
113   114        209302150          DEVANSHU RASTOGI              50   
114   115        209302169            DIVYANSH MALIK              53   
115   116        209302317  PRAJESH PRANESH YEOTIKAR              53   
116   117        209309065           SIDDHANT KESHAV              53   

     External Marks  Total Rev_Grade  
0                34     89         A  
1                34     89         A  
2                37     88         A  
3                34     88         A  
4                36     88         A  
..              ...    ...       ...  
112              33     79         A  
113              32     79         A  
114              34     79         A  
115              36     79         A  
116              34     79         A  

[117 rows x 7 columns]

In [ ]:
data['Rev_Grade'].replace("A+",10,inplace = True)
data['Rev_Grade'].replace("A",9,inplace = True)
data['Rev_Grade'].replace("B",8,inplace = True)
data['Rev_Grade'].replace("C",7,inplace = True)
data['Rev_Grade'].replace("D",6,inplace = True)

data

S.No  Registration No              Student Name  Internal Marks  \
0       1        209301007           NIKHIL BHANDARI              47   
1       2        209301011                 IVA SETHI              47   
2       3        209301020      JASKARAN SINGH BARMI              49   
3       4        209301037               NITYA ARORA              47   
4       5        209301041    HARSHIT KUMAR METPALLY              49   
..    ...              ...                       ...             ...   
112   113        209302115         TANISHA CHAUDHARY              54   
113   114        209302150          DEVANSHU RASTOGI              50   
114   115        209302169            DIVYANSH MALIK              53   
115   116        209302317  PRAJESH PRANESH YEOTIKAR              53   
116   117        209309065           SIDDHANT KESHAV              53   

     External Marks  Total  Rev_Grade  
0                34     89          9  
1                34     89          9  
2                37     88          9  
3                34     88          9  
4                36     88          9  
..              ...    ...        ...  
112              33     79          9  
113              32     79          9  
114              34     79          9  
115              36     79          9  
116              34     79          9  

[117 rows x 7 columns]

In [ ]:
data['Rev_Grade'].unique()

array([ 9,  8,  7, 10])

In [ ]:
data.rename(columns={"Rev_Grade":"Grade_Point"},inplace = True)

In [ ]:
data

S.No  Registration No              Student Name  Internal Marks  \
0       1        209301007           NIKHIL BHANDARI              47   
1       2        209301011                 IVA SETHI              47   
2       3        209301020      JASKARAN SINGH BARMI              49   
3       4        209301037               NITYA ARORA              47   
4       5        209301041    HARSHIT KUMAR METPALLY              49   
..    ...              ...                       ...             ...   
112   113        209302115         TANISHA CHAUDHARY              54   
113   114        209302150          DEVANSHU RASTOGI              50   
114   115        209302169            DIVYANSH MALIK              53   
115   116        209302317  PRAJESH PRANESH YEOTIKAR              53   
116   117        209309065           SIDDHANT KESHAV              53   

     External Marks  Total  Grade_Point  
0                34     89            9  
1                34     89            9  
2                37     88            9  
3                34     88            9  
4                36     88            9  
..              ...    ...          ...  
112              33     79            9  
113              32     79            9  
114              34     79            9  
115              36     79            9  
116              34     79            9  

[117 rows x 7 columns]

In [ ]:
cp=data.copy()

In [ ]:
cp

S.No  Registration No              Student Name  Internal Marks  \
0       1        209301007           NIKHIL BHANDARI              47   
1       2        209301011                 IVA SETHI              47   
2       3        209301020      JASKARAN SINGH BARMI              49   
3       4        209301037               NITYA ARORA              47   
4       5        209301041    HARSHIT KUMAR METPALLY              49   
..    ...              ...                       ...             ...   
112   113        209302115         TANISHA CHAUDHARY              54   
113   114        209302150          DEVANSHU RASTOGI              50   
114   115        209302169            DIVYANSH MALIK              53   
115   116        209302317  PRAJESH PRANESH YEOTIKAR              53   
116   117        209309065           SIDDHANT KESHAV              53   

     External Marks  Total  Grade_Point  
0                34     89            9  
1                34     89            9  
2                37     88            9  
3                34     88            9  
4                36     88            9  
..              ...    ...          ...  
112              33     79            9  
113              32     79            9  
114              34     79            9  
115              36     79            9  
116              34     79            9  

[117 rows x 7 columns]

In [ ]:
cp.drop('Student Name',axis=1,inplace=True)

In [ ]:
cp.drop('S.No',axis=1,inplace=True)

In [ ]:
cp

Registration No  Internal Marks  External Marks  Total  Grade_Point
0          209301007              47              34     89            9
1          209301011              47              34     89            9
2          209301020              49              37     88            9
3          209301037              47              34     88            9
4          209301041              49              36     88            9
..               ...             ...             ...    ...          ...
112        209302115              54              33     79            9
113        209302150              50              32     79            9
114        209302169              53              34     79            9
115        209302317              53              36     79            9
116        209309065              53              34     79            9

[117 rows x 5 columns]

In [ ]:
cp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Registration No  117 non-null    int64
 1   Internal Marks   117 non-null    int64
 2   External Marks   117 non-null    int64
 3   Total            117 non-null    int64
 4   Grade_Point      117 non-null    int64
dtypes: int64(5)
memory usage: 4.7 KB


***LINEAR REGRESSION***

In [ ]:
x = pd.DataFrame(cp,columns=['Internal Marks','External Marks'])
y = pd.DataFrame(cp,columns=['Total','Grade_Point'])

In [ ]:
x

Internal Marks  External Marks
0                47              34
1                47              34
2                49              37
3                47              34
4                49              36
..              ...             ...
112              54              33
113              50              32
114              53              34
115              53              36
116              53              34

[117 rows x 2 columns]

In [ ]:
y

Total  Grade_Point
0       89            9
1       89            9
2       88            9
3       88            9
4       88            9
..     ...          ...
112     79            9
113     79            9
114     79            9
115     79            9
116     79            9

[117 rows x 2 columns]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

lr=LinearRegression()

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,shuffle=True,random_state=1)

In [ ]:
x_train

Internal Marks  External Marks
32               45              33
78               44              29
19               47              34
116              53              34
27               37              27
..              ...             ...
9                49              34
72               50              33
12               45              33
107              48              31
37               51              37

[81 rows x 2 columns]

In [ ]:
y_train

Total  Grade_Point
32      78            8
78      71            8
19      86            9
116     79            9
27      64            7
..     ...          ...
9       87            9
72      82            9
12      78            8
107     79            9
37      85            9

[81 rows x 2 columns]

In [ ]:
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
lr.score(x_test,y_test)

0.7833900003320342

In [ ]:
res=np.array([[]])

In [ ]:
res = lr.predict(np.array([[53,35]]))

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
res

array([[84.74674341,  9.35226373]])

In [ ]:
if(res[0][1]>9 and res[0][1]<=10):
  print("Grade : ",'A+')
elif(res[0][1]>8 and res[0][1]<=9):
  print("Grade : ",'A')
elif(res[0][1]>7 and res[0][1]<=8):
  print("Grade : ",'B')
elif(res[0][1]>6 and res[0][1]<=7):
  print("Grade : ",'C')
elif(res[0][1]>5 and res[0][1]<=6):
  print("Grade : ",'D')

Grade :  A+


In [ ]:
import pickle

In [ ]:
pickle.dump(lr,open('model1.pkl','wb'))

Tensor Flow Implementation

In [ ]:
import tensorflow as tf
from tensorflow import keras,lite

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(15, input_dim=2, activation='relu'))
model.add(Dense(1, activation='linear'))

In [ ]:
model.compile(loss='mse', optimizer='adam', metrics=['mse', 'mae'])

In [ ]:
prediction = model.fit(x_train, y_train, epochs=500, validation_split=0.2)

Epoch 1/500
2/2 [==============================] - 0s 108ms/step - loss: 1248.0483 - mse: 1248.0483 - mae: 35.0000 - val_loss: 1311.4958 - val_mse: 1311.4958 - val_mae: 35.9706
Epoch 2/500
2/2 [==============================] - 0s 40ms/step - loss: 1248.0398 - mse: 1248.0398 - mae: 35.0000 - val_loss: 1311.4895 - val_mse: 1311.4895 - val_mae: 35.9706
Epoch 3/500
2/2 [==============================] - 0s 50ms/step - loss: 1248.0332 - mse: 1248.0332 - mae: 35.0000 - val_loss: 1311.4795 - val_mse: 1311.4795 - val_mae: 35.9706
Epoch 4/500
2/2 [==============================] - 0s 39ms/step - loss: 1248.0299 - mse: 1248.0299 - mae: 35.0000 - val_loss: 1311.4918 - val_mse: 1311.4918 - val_mae: 35.9706
Epoch 5/500
2/2 [==============================] - 0s 37ms/step - loss: 1248.0231 - mse: 1248.0231 - mae: 35.0000 - val_loss: 1311.4595 - val_mse: 1311.4595 - val_mae: 35.9706
Epoch 6/500
2/2 [==============================] - 0s 40ms/step - loss: 1248.0171 - mse: 1248.0171 - mae: 35.0000 - val

In [ ]:
x_test.shape

(36, 2)

In [ ]:
model.evaluate(x_test, y_test, batch_size=15)

3/3 [==============================] - 0s 3ms/step - loss: 1281.2804 - mse: 1281.2804 - mae: 35.5972


[1281.2803955078125, 1281.2803955078125, 35.59722137451172]

In [ ]:
y_pred = model.predict(x_test).flatten()
y_pred

array([40.238037, 31.861353, 45.200584, 47.93135 , 37.585922, 45.200584,
       48.273033, 48.273033, 46.27716 , 45.200584, 44.045372, 50.66211 ,
       47.055084, 45.043312, 41.89222 , 45.12195 , 43.54641 , 46.854767,
       48.430313, 44.465706, 43.54641 , 45.62092 , 33.095207, 41.89222 ,
       42.811516, 46.27716 , 42.968796, 44.465706, 46.43199 , 46.61885 ,
       48.273033, 39.240105, 44.701622, 43.96673 , 44.62298 , 48.50895 ],
      dtype=float32)

In [ ]:
res_keras = model.predict(np.array([[50,32]]))
res_keras

array([[45.200584]], dtype=float32)

In [ ]:
x_test

Internal Marks  External Marks
69               44              29
46               39              18
58               50              32
114              53              34
73               42              26
98               50              32
31               51              37
53               51              37
65               51              33
96               50              32
95               48              32
97               56              36
2                49              37
62               48              34
110              46              30
55               49              33
103              48              31
100              52              33
66               53              35
44               47              34
77               48              31
17               49              34
81               42              17
74               46              30
56               45              33
94               51              33
35               47              31
38               47              34
93               48              37
48               49              36
33               51              37
59               44              27
92               50              31
42               47              33
10               49              32
85               54              34

In [ ]:
y_test

Total  Grade_Point
69      74            8
46      57            7
58      82            9
114     79            9
73      73            8
98      81            9
31      85            9
53      83            9
65      82            9
96      81            9
95      81            9
97      92           10
2       88            9
62      82            9
110     68            8
55      83            9
103     80            9
100     80            9
66      82            9
44      84            9
77      82            9
17      87            9
81      59            7
74      73            8
56      76            8
94      81            9
35      78            8
38      85            9
93      81            9
48      83            9
33      85            9
59      76            8
92      81            9
42      85            9
10      87            9
85      81            9

In [ ]:
keras_file = "se_project.h5"
tf.keras.models.save_model()

In [ ]:
model = lr.fit(x_train,y_train)

# create a TF model with the same architecture
tf_model = tf.keras.models.Sequential()
tf_model.add(tf.keras.Input(shape=(2,)))
tf_model.add(tf.keras.layers.Dense(2))

# assign the parameters from sklearn to the TF model
tf_model.layers[0].weights[0].assign(model.coef_.transpose())
tf_model.layers[0].bias.assign(model.intercept_)

# verify the models do the same prediction
#assert np.all((tf_model(x) > 0)[:, 0].numpy() == model.predict(x))

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([25.631708 ,  1.6959783], dtype=float32)>

In [ ]:
tf_model.compile(loss='mse', optimizer='adam', metrics=['mse', 'mae'])

In [ ]:
pred_model = tf_model.fit(x_train, y_train, epochs=500, validation_split=0.2)

Epoch 1/500
2/2 [==============================] - 1s 248ms/step - loss: 8.4229 - mse: 8.4229 - mae: 1.7086 - val_loss: 9.3449 - val_mse: 9.3449 - val_mae: 1.9183
Epoch 2/500
2/2 [==============================] - 0s 29ms/step - loss: 8.3595 - mse: 8.3595 - mae: 1.7016 - val_loss: 9.5094 - val_mse: 9.5094 - val_mae: 1.9178
Epoch 3/500
2/2 [==============================] - 0s 26ms/step - loss: 8.3421 - mse: 8.3421 - mae: 1.7015 - val_loss: 9.6901 - val_mse: 9.6901 - val_mae: 1.9254
Epoch 4/500
2/2 [==============================] - 0s 27ms/step - loss: 8.3096 - mse: 8.3096 - mae: 1.6997 - val_loss: 9.8111 - val_mse: 9.8111 - val_mae: 1.9306
Epoch 5/500
2/2 [==============================] - 0s 26ms/step - loss: 8.3246 - mse: 8.3246 - mae: 1.6992 - val_loss: 9.9640 - val_mse: 9.9640 - val_mae: 1.9448
Epoch 6/500
2/2 [==============================] - 0s 24ms/step - loss: 8.3015 - mse: 8.3015 - mae: 1.6969 - val_loss: 10.0527 - val_mse: 10.0527 - val_mae: 1.9526
Epoch 7/500
2/2 [========

In [ ]:
tf_model.evaluate(x_test, y_test, batch_size=15)

3/3 [==============================] - 0s 3ms/step - loss: 5.9364 - mse: 5.9364 - mae: 1.5311


[5.936374187469482, 5.936374187469482, 1.531141996383667]

In [ ]:
res_keras = tf_model.predict(np.array([[50,32]]))
res_keras

array([[79.41146 ,  8.835081]], dtype=float32)

In [ ]:
keras_file = "se_final.h5"
tf.keras.models.save_model(tf_model,keras_file)
converter = lite.TFLiteConverter.from_keras_model(tf_model)
keras_model = converter.convert()

open("se_final.tflite","wb").write(keras_model)

INFO:tensorflow:Assets written to: /tmp/tmpzimzfjgn/assets


904